# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: >
          (?x)^(
            project/app/src/main/res/values-[a-z]{2}/strings.xml
          )$
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
            project/app/objectbox-models/default.json|
            project/app/src/main/res/values-[a-z]{2}/strings.xml
          )$
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-xml
      - id: check-toml
      - id: check-added-large-files
      - id: mixed-line-ending
        exclude: project/gradlew.bat
        args: ["--fix=lf"]
  - repo: local
    hooks:
      - id: unit-test
        name: Run unit tests
        description: Runs unit-tests
        entry: ./project/gradlew -p project testGmsDebugUnitTest
        pass_filenames: false
        language: system
      - id: ktlint
        name: ktlint
        description: Ktlints
        entry: ./project/gradlew -p project ktlintCheck
        pass_filenames: false
        language: system
