language: android
before_script: cd project
android:
    components:
        - tools
        - platform-tools
        - ildTools version used by your project
        - build-tools-26.0.2
        - android-27
        - extra-google-google_play_services