language: android
before_script: cd project
# Workaround to get travis to user Android 27: https://github.com/travis-ci/travis-ci/issues/8874
before_install:
- yes | sdkmanager "platforms;android-27"
android:
    components:
        - tools
        - platform-tools
        - ildTools version used by your project
        - build-tools-26.0.2
        - android-27
        - extra-google-google_play_services
