---
# Machine image tags listed at https://circleci.com/developer/machine/image/android
version: 2.1

setup: true

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

orbs:
  continuation: circleci/continuation@0.3.1
  path-filtering: circleci/path-filtering@0.1.3

jobs:
  setup-build-job:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - path-filtering/set-parameters:
          base-revision: master
          output-path: /tmp/pipeline-params.json
          mapping: |
            .circleci\/.*\.yml source-changed true
            project\/app\/src\/.* source-changed true
            project\/buildSrc\/src\/.* source-changed true
            project\/.*\.gradle\.kts source-changed true
            project\/gradle\/libs.versions.toml source-changed true
            project\/gradle\/wrapper\/gradle-wrapper.properties source-changed true
      - when:
          condition:
            or:
              - equal:
                  ["smoke-test-required", << pipeline.parameters.GHA_Meta >>]
              - equal: ["trigger-smoke-test", << pipeline.git.branch >>]
          steps:
            - run: |
                cat /tmp/pipeline-params.json | jq '. += { "smoke-test-required" : true}' >  /tmp/pipeline-params.json.tmp
                mv /tmp/pipeline-params.json.tmp /tmp/pipeline-params.json
      - when:
          condition:
            or:
              - equal:
                  [
                    "integration-test-required",
                    << pipeline.parameters.GHA_Meta >>,
                  ]
              - equal: ["trigger-integration-test", << pipeline.git.branch >>]
          steps:
            - run: |
                cat /tmp/pipeline-params.json | jq '. += { "integration-test-required" : true}' >  /tmp/pipeline-params.json.tmp
                mv /tmp/pipeline-params.json.tmp /tmp/pipeline-params.json
      - continuation/continue:
          parameters: /tmp/pipeline-params.json
          configuration_path: .circleci/continue-config.yml
workflows:
  setup-build-workflow:
    jobs:
      - setup-build-job
