version: 2.1

parameters:
  source-changed:
    type: boolean
    default: false
  smoke-test-required:
    type: boolean
    default: false
  integration-test-required:
    type: boolean
    default: false
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""
  jdk-version:
    type: integer
    default: 17

workflows:
  build-integration-test-publish:
    when:
      and:
        - equal: [master, << pipeline.git.branch >>]
        - << pipeline.parameters.source-changed >>
    jobs:
      - build-release:
          context: Android Deploy Credentials
      - fdroid-scanner:
          requires:
            - build-release
      - unit-test:
          requires:
            - build-release
      - lint:
          requires:
            - build-release
      - ui-tests:
          matrix:
            parameters:
              flavor:
                - oss
                - gms
          name: <<matrix.flavor>>-ui-tests
          requires:
            - lint
            - unit-test
            - build-release
      - publish-to-play-store:
          context: Android Deploy Credentials
          requires:
            - oss-ui-tests
            - gms-ui-tests

  smoke-test:
    when: << pipeline.parameters.smoke-test-required >>
    jobs:
      - unit-test:
          upload-coverage: false
      - ui-tests:
          flavor: gms
          parallelism: 1
          only-smoke-tests: true
          name: smoke-test
          requires:
            - unit-test
      - pr-test-complete:
          requires:
            - smoke-test

  integration-test:
    when: << pipeline.parameters.integration-test-required >>
    jobs:
      - unit-test:
          upload-coverage: true
      - ui-tests:
          matrix:
            parameters:
              flavor:
                - oss
                - gms
          name: <<matrix.flavor>>-ui-tests
          requires:
            - unit-test
      - pr-test-complete:
          requires:
            - gms-ui-tests
            - oss-ui-tests

executors:
  android-docker:
    docker:
      - image: cimg/android:2022.09
  android-machine:
    machine:
      image: android:2022.09.1

commands:
  android-init:
    steps:
      - checkout
      - android/accept-licenses
      - run: |
          sudo apt-get update
      - android/change-java-version:
          java-version: << pipeline.parameters.jdk-version >>
  restore-gradle-cache:
    parameters:
      version:
        type: string
        default: v4-jvm17
    steps:
      - run:
          name: Generate Gradle buildfiles seed
          command: |
            find . -name 'build.gradle.kts' -o -name 'libs.versions.toml' -o -name 'gradle-wrapper.properties'  |
            sort      |
            xargs cat |
            shasum    |
            awk '{print $1}' > /tmp/gradle_buildfiles_cache_seed
      - run:
          name: Generate Gradle sources seed
          command: |
            find . -path "./project/app/src/*" -a  \( -name "*.kt" -o -name "*.java" \) |
            sort      |
            xargs cat |
            shasum    |
            awk '{print $1}' > /tmp/gradle_sources_cache_seed
      - restore_cache:
          keys:
            - gradle-<< parameters.version >>-{{ arch }}-buildscript-{{ checksum "/tmp/gradle_buildfiles_cache_seed"}}-sources-{{ checksum "/tmp/gradle_sources_cache_seed"}}
            - gradle-<< parameters.version >>-{{ arch }}-buildscript-{{ checksum "/tmp/gradle_buildfiles_cache_seed"}}-
            - gradle-<< parameters.version >>-{{ arch }}-
            - gradle-<< parameters.version >>-

  save-gradle-cache:
    parameters:
      version:
        type: string
        default: v4-jvm17
    steps:
      - save_cache:
          key: >-
            gradle-<< parameters.version >>-{{ arch }}-buildscript-{{ checksum "/tmp/gradle_buildfiles_cache_seed"}}-sources-{{ checksum "/tmp/gradle_sources_cache_seed"}}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
  run-andoid-emulator-and-tests:
    steps:
      - android/start-emulator-and-run-tests:
          additional-avd-args: "-d pixel_3a -c 1G"
          additional-emulator-args: "-memory 4096 -cores 3"
          test-command: $GRADLE_TEST_COMMAND
          system-image: $SYSTEM_IMAGE
          restore-gradle-cache-post-emulator-launch: false
          run-tests-working-directory: ./project
          post-emulator-wait-steps:
            # Set up the device for the right location service settings
            - run: adb shell settings put secure location_providers_allowed +gps && adb shell settings put secure location_providers_allowed +network && adb shell settings put secure location_mode 3 && adb shell settings put global heads_up_notifications_enabled 0
            # Restart zygote to make sure it picks up the right heap setting, otherwise mystery OOMs will happen
            - run: |
                for i in 1 2 3; do adb root && break || sleep 15; done
            - run: sleep 5
            - run: adb shell setprop ctl.restart zygote
            - run:
                background: true
                command: |
                  adb logcat
                name: Logcat
          post-emulator-launch-assemble-command: ""
          run-logcat: false
          max-tries: 2
          no-output-timeout: 30m
          save-gradle-cache: false

orbs:
  android: circleci/android@2.1.0
  codecov: codecov/codecov@3.2.4

jobs:
  build-release:
    executor: android-docker
    resource_class: large
    steps:
      - android-init
      - restore-gradle-cache
      - run:
          name: Set credentials
          command: |
            echo -n $GOOGLE_CLOUD_SERVICE_ACCOUNT_CREDENTIALS_BASE64 | base64 -d > project/app/owntracks-android-gcloud-creds.json
            echo -n $KEYSTORE_BASE64 | base64 -d > project/owntracks.release.keystore.jks
      - run:
          name: Build
          command: |
            ./project/gradlew -p ./project assembleDebug assembleRelease assembleAndroidTest assembleGmsReleaseUnitTest :app:compileOssReleaseSources :app:packageGmsReleaseBundle app:assembleGmsDebugAndroidTest app:assembleOssDebugAndroidTest --scan
      - save-gradle-cache
      - persist_to_workspace:
          root: project/app/build/outputs/apk/
          paths:
            - "**"

  fdroid-scanner:
    docker:
      - image: registry.gitlab.com/fdroid/docker-executable-fdroidserver:master
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: project/app/build/outputs/apk/
      - run:
          name: Fdroid Scanner
          command: |
            /usr/local/bin/fdroid scanner project/app/build/outputs/apk/oss/release/app-oss-release.apk

  unit-test:
    parameters:
      upload-coverage:
        type: boolean
        default: true
    executor: android-docker
    resource_class: large
    steps:
      - android-init
      - restore-gradle-cache
      - run:
          name: Unit Test
          command: |
            ./project/gradlew -p ./project jacocoTestGmsReleaseUnitTestReport --scan
      - store_test_results:
          path: project/app/build/test-results/testGmsReleaseUnitTest
      - when:
          condition: << parameters.upload-coverage >>
          steps:
            - codecov/upload:
                file: project/app/build/jacoco/jacoco.xml
                flags: unittests

  lint:
    executor: android-docker
    resource_class: medium+
    steps:
      - android-init
      - restore-gradle-cache
      - run:
          name: Lint
          command: |
            ./project/gradlew -p ./project lint --scan
      - store_artifacts:
          path: project/app/build/reports/lint-results.html
          destination: lint-report

  ui-tests:
    parameters:
      flavor:
        type: string
        default: oss
      parallelism:
        type: integer
        default: 4
      android-api-version:
        type: string
        default: "29"
      only-smoke-tests:
        type: boolean
        default: false
    executor: android-machine
    resource_class: large
    parallelism: << parameters.parallelism >>
    environment:
      GRADLE_OPTS: "-Dkotlin.compiler.execution.strategy=in-process"
    steps:
      - android-init
      - restore-gradle-cache
      - run:
          name: Prepare parameterised test command
          command: |
            export FLAVOR="<< parameters.flavor >>"
            if [ << parameters.only-smoke-tests >> = "true" ]; then
              gradletask="connectedGmsDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.annotation=org.owntracks.android.testutils.SmokeTest"
            else
              gradletask="create${FLAVOR^}DebugCoverageReport"
            fi
            echo "export GRADLE_TEST_COMMAND=\"./gradlew $gradletask --scan --no-daemon --max-workers 2\"" >> $BASH_ENV
            source $BASH_ENV
            echo "Gradle test command: $GRADLE_TEST_COMMAND"

      - run:
          name: Prepare parameterised system image
          command: |
            if [ << parameters.flavor >> = "gms" ]; then
              image_type="google_apis"
            else
              image_type="default"
            fi
            echo "export SYSTEM_IMAGE=\"system-images;android-<< parameters.android-api-version >>;$image_type;x86_64\"" >> $BASH_ENV
            # Debug only
            source $BASH_ENV
            echo "Emulator system image: $SYSTEM_IMAGE"

      - run-andoid-emulator-and-tests
      - save-gradle-cache
      - when:
          condition:
            not: << parameters.only-smoke-tests >>
          steps:
            - store_test_results:
                path: project/app/build/outputs/androidTest-results/connected/flavors/<< parameters.flavor >>/
            - store_artifacts:
                path: project/app/build/reports/androidTests
                destination: espresso-report-<< parameters.flavor >>
            - codecov/upload:
                file: reports/coverage/**/report.xml
                flags: uitests

  publish-to-play-store:
    executor: android-docker
    resource_class: medium
    steps:
      - android-init
      - restore-gradle-cache
      - run:
          name: Set credentials
          command: |
            echo -n $GOOGLE_CLOUD_SERVICE_ACCOUNT_CREDENTIALS_BASE64 | base64 -d > project/app/owntracks-android-gcloud-creds.json
            echo -n $KEYSTORE_BASE64 | base64 -d > project/owntracks.release.keystore.jks
      - attach_workspace:
          at: project/app/build/outputs/apk/
      - run:
          name: Build
          command: |
            ./project/gradlew -p ./project publishGmsReleaseBundle --scan
      - store_artifacts:
          path: project/app/build/outputs/apk/gms/release/app-gms-release.apk
          destination: gms-apk
      - store_artifacts:
          path: project/app/build/outputs/apk/oss/release/app-oss-release.apk
          destination: oss-apk
  # Stub job that allows us to gate GH PRs on either inegration or smoke test complete
  pr-test-complete:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run: echo "done"
