name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Build & Test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: project
      timeout-minutes: 10
    - name: Test with Gradle on the emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: cd project && ./gradlew test connectedAndroidTest check jacocoTestReport
      timeout-minutes: 10
    - name: Gather xunit files into a single dir
      run: mkdir -p ./project/app/build/test-results/collected/ && cp ./project/app/build/test-results/testDebugUnitTest/*.xml ./project/app/build/test-results/collected/ && cp ./project/app/build/outputs/androidTest-results/connected/*.xml ./project/app/build/test-results/collected/
      if: always()
    - uses: growse/xunit-mattermost-reporter@v1
      with:
        mattermostWebhookUrl: ${{ secrets.MATTERMOST_WEBHOOK }}
        xUnitTestPath: "./project/app/build/test-results/collected/"
      if: always()
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: test
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Decrypt secrets
        env:
            GOOGLE_CLOUD_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_CREDENTIALS }}
            KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
            echo -n $GOOGLE_CLOUD_SERVICE_ACCOUNT_CREDENTIALS > project/app/owntracks-android-7a7fe209cba5.json
            echo -n $KEYSTORE_BASE64 | base64 -d > project/owntracks.release.keystore.jks
      - name: Publish play store bundle
        timeout-minutes: 10
        run: ./gradlew publishBundle
        working-directory: project
        env:
            KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
            ORG_GRADLE_PROJECT_google_maps_api_key: ${{ secrets.GOOGLE_MAPS_API_KEY }}
