---
name: Build and Test

"on":
  push:
    paths:
      - ".github/workflows/build-and-test.yml"
      - "project/app/src/**"
      - "project/app/*.pro"
      - "project/buildSrc/src/**"
      - "project/*.gradle.kts"
      - "project/gradle/wrapper/gradle-wrapper.properties"
    branches:
      - master
      - gh-readonly-queue/master/**
  pull_request:
    branches:
      - master

# if: ${{ !github.event.pull_request.head.repo.fork && github.event.label && ( github.event.label.name == 'smoke-test-required' || github.event.label.name == 'integration-test-required') }}

jobs:
  build-test-lint:
    name: Build, test & lint
    runs-on: macos-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Create keystore
        run: |
          echo -n $KEYSTORE_BASE64 | base64 -d > project/owntracks.release.keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: Gradle build
        run: |
          ./project/gradlew -p project \
            --scan \
              assembleDebug \
              assembleRelease \
              assembleAndroidTest \
              assembleGmsReleaseUnitTest \
              :app:compileOssReleaseSources \
              :app:packageGmsReleaseBundle \
              :app:assembleGmsDebugAndroidTest \
              :app:assembleOssDebugAndroidTest
        env:
          KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}

      - name: Upload apk artifact
        uses: actions/upload-artifact@v3
        with:
          name: apks
          path: |
            project/app/build/outputs/apk/oss/release/app-oss-release.apk
            project/app/build/outputs/apk/gms/release/app-gms-release.apk

      - name: Unit Test
        run: ./project/gradlew -p project app:createGmsDebugUnitTestCoverageReport
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./project/app/build/reports/coverage/test/gms/debug/report.xml
          flags: unittests
      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: "**/build/test-results/test*UnitTest/TEST-*.xml"

      - name: Lint
        run: ./project/gradlew -p project lint

      - name: Upload lint report
        uses: actions/upload-artifact@v3
        with:
          name: lint-report
          path: project/app/build/reports/lint-results-gmsDebug.html

  fdroid-scanner:
    name: F-Droid scanner
    runs-on: ubuntu-latest
    needs: build-test-lint
    container:
      image: registry.gitlab.com/fdroid/docker-executable-fdroidserver:master
    steps:
      - name: Download APK
        uses: actions/download-artifact@v3
        with:
          name: apks
      - name: Scan OSS APK
        run: |
          . /etc/profile.d/bsenv.sh && GRADLE_USER_HOME=${home_vagrant}/.gradle ${fdroidserver}/fdroid scanner oss/release/app-oss-release.apk
