name: Auto-Label PRs

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@v4.2.0
        with:
          repo-token: "${{ secrets.PAT }}"
